run:
	@python3 main.py

setup:
	@pip3 install -r requirements.txt

pack-extension:
	/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --pack-extension=/Users/trent/Library/Application\ Support/Google/Chrome/Default/Extensions/nkbihfbeogaeaoehlefnkodbefgpgknn